/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as ipaLicenseTermsSol from "./IPALicenseTerms.sol";
export * as interfaces from "./interfaces";
export { CopyrightNFT__factory } from "./CopyrightNFT__factory";
export { SimpleNFT__factory } from "./SimpleNFT__factory";
